// Generated by: gen
// TypeWriter: slice
// Directive: +gen on ImageItem

package main

// ImageItemSlice is a slice of type ImageItem. Use it where you would use []ImageItem.
type ImageItemSlice []ImageItem

// SelectRemoteImageItem projects a slice of RemoteImageItem from ImageItemSlice, typically called a map in other frameworks. See: http://clipperhouse.github.io/gen/#Select
func (rcv ImageItemSlice) SelectRemoteImageItem(fn func(ImageItem) RemoteImageItem) (result []RemoteImageItem) {
	for _, v := range rcv {
		result = append(result, fn(v))
	}
	return
}
